"""empty message

Revision ID: 462aa29f4fa8
Revises: 5ac571346cbe
Create Date: 2020-03-07 23:08:24.727634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '462aa29f4fa8'
down_revision = '5ac571346cbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('app_instances_department_fkey', 'app_instances', type_='foreignkey')
    op.create_foreign_key(None, 'app_instances', 'student_accounts', ['department', 'number', 'admission_year'], ['department', 'number', 'admission_year'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'app_instances', type_='foreignkey')
    op.create_foreign_key('app_instances_department_fkey', 'app_instances', 'students', ['department', 'number', 'admission_year'], ['department', 'number', 'admission_year'])
    # ### end Alembic commands ###
