"""empty message

Revision ID: 572c95b37b57
Revises: 
Create Date: 2020-02-20 14:33:59.352329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '572c95b37b57'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=64), nullable=False),
    sa.Column('event_description', sa.Text(), nullable=False),
    sa.Column('venue', sa.String(length=64), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staffs',
    sa.Column('staff_id', sa.String(length=64), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('department', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('staff_id')
    )
    op.create_table('students',
    sa.Column('adm_number', sa.String(length=64), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('middle_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('admission_year', sa.Integer(), nullable=False),
    sa.Column('course', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('adm_number')
    )
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sender_id', sa.String(length=64), nullable=False),
    sa.Column('posted_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['staffs.staff_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff_accounts',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['staffs.staff_id'], ),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('student_accounts',
    sa.Column('adm_number', sa.String(), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['adm_number'], ['students.adm_number'], ),
    sa.PrimaryKeyConstraint('adm_number')
    )
    op.create_table('app_instances',
    sa.Column('adm_number', sa.String(), nullable=False),
    sa.Column('token', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['adm_number'], ['student_accounts.adm_number'], ),
    sa.PrimaryKeyConstraint('adm_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_instances')
    op.drop_table('student_accounts')
    op.drop_table('staff_accounts')
    op.drop_table('announcements')
    op.drop_table('students')
    op.drop_table('staffs')
    op.drop_table('events')
    # ### end Alembic commands ###
