"""empty message

Revision ID: 5ac571346cbe
Revises: 
Create Date: 2020-03-07 22:50:53.235046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ac571346cbe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('department_code', sa.CHAR(length=3), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('department_code')
    )
    op.create_table('schools',
    sa.Column('school_code', sa.CHAR(length=3), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('school_code')
    )
    op.create_table('students',
    sa.Column('department', sa.CHAR(length=3), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('admission_year', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('middle_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('department', 'number', 'admission_year')
    )
    op.create_table('app_instances',
    sa.Column('department', sa.CHAR(length=3), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('admission_year', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=240), nullable=False),
    sa.ForeignKeyConstraint(['department', 'number', 'admission_year'], ['students.department', 'students.number', 'students.admission_year'], ),
    sa.PrimaryKeyConstraint('department', 'number', 'admission_year')
    )
    op.create_table('staffs',
    sa.Column('staff_id', sa.String(length=64), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('department_code', sa.CHAR(length=3), nullable=False),
    sa.Column('school_code', sa.CHAR(length=3), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['department_code'], ['departments.department_code'], ),
    sa.ForeignKeyConstraint(['school_code'], ['schools.school_code'], ),
    sa.PrimaryKeyConstraint('staff_id')
    )
    op.create_table('student_accounts',
    sa.Column('department', sa.CHAR(length=3), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('admission_year', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['department', 'number', 'admission_year'], ['students.department', 'students.number', 'students.admission_year'], ),
    sa.PrimaryKeyConstraint('department', 'number', 'admission_year')
    )
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sender_id', sa.String(length=64), nullable=False),
    sa.Column('posted_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['staffs.staff_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=64), nullable=False),
    sa.Column('event_description', sa.Text(), nullable=False),
    sa.Column('venue', sa.String(length=64), nullable=False),
    sa.Column('creator_id', sa.String(length=64), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['staffs.staff_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff_accounts',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['staffs.staff_id'], ),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff_accounts')
    op.drop_table('events')
    op.drop_table('announcements')
    op.drop_table('student_accounts')
    op.drop_table('staffs')
    op.drop_table('app_instances')
    op.drop_table('students')
    op.drop_table('schools')
    op.drop_table('departments')
    # ### end Alembic commands ###
