"""empty message

Revision ID: bc6923372b8f
Revises: 
Create Date: 2020-03-04 16:11:43.319561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc6923372b8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sender_id', sa.String(length=64), nullable=False),
    sa.Column('posted_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['staffs.staff_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_instances',
    sa.Column('adm_number', sa.String(), nullable=False),
    sa.Column('token', sa.String(length=240), nullable=False),
    sa.ForeignKeyConstraint(['adm_number'], ['student_accounts.adm_number'], ),
    sa.PrimaryKeyConstraint('adm_number')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=64), nullable=False),
    sa.Column('event_description', sa.Text(), nullable=False),
    sa.Column('venue', sa.String(length=64), nullable=False),
    sa.Column('creator_id', sa.String(length=64), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['staffs.staff_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff_accounts',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['staffs.staff_id'], ),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff_accounts')
    op.drop_table('events')
    op.drop_table('app_instances')
    op.drop_table('announcements')
    # ### end Alembic commands ###
