"""empty message

Revision ID: dcf544251db0
Revises: cafe7c2d33c7
Create Date: 2020-02-20 16:39:45.711312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcf544251db0'
down_revision = 'cafe7c2d33c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('department_code', sa.CHAR(length=3), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('department_code')
    )
    op.create_table('schools',
    sa.Column('school_code', sa.CHAR(length=3), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('school_code')
    )
    op.add_column('staffs', sa.Column('department_code', sa.CHAR(length=3), nullable=True))
    op.add_column('staffs', sa.Column('school_code', sa.CHAR(length=3), nullable=True))
    op.create_foreign_key(None, 'staffs', 'schools', ['school_code'], ['school_code'])
    op.create_foreign_key(None, 'staffs', 'departments', ['department_code'], ['department_code'])
    op.drop_column('staffs', 'department')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staffs', sa.Column('department', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'staffs', type_='foreignkey')
    op.drop_constraint(None, 'staffs', type_='foreignkey')
    op.drop_column('staffs', 'school_code')
    op.drop_column('staffs', 'department_code')
    op.drop_table('schools')
    op.drop_table('departments')
    # ### end Alembic commands ###
