"""empty message

Revision ID: ddcc9af4889b
Revises: dcf544251db0
Create Date: 2020-02-20 16:42:18.239128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddcc9af4889b'
down_revision = 'dcf544251db0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staffs', 'department_code',
               existing_type=sa.CHAR(length=3),
               nullable=False)
    op.alter_column('staffs', 'school_code',
               existing_type=sa.CHAR(length=3),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staffs', 'school_code',
               existing_type=sa.CHAR(length=3),
               nullable=True)
    op.alter_column('staffs', 'department_code',
               existing_type=sa.CHAR(length=3),
               nullable=True)
    # ### end Alembic commands ###
